script: true
install: true
notifications: 
  hipchat: 
    template: 
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href='https://pypi.python.org/pypi/m3-ui/%{branch}'>%{branch}</a>)"
    rooms:
    - b7098c17bc3283dc7ca388b68e3ca3@m3
    format: html
language: python
deploy: 
  provider: pypi
  password: 
    secure: GQDZaqpjU8lNeIeGKRv5ZIPGVx0Yzowex8pZp+0y9mqI+JKnyrpDTzq2aIbVkXu7IZWNO+w2UmDQdi6wpSUwqoltNOm/Jb1wsaE8GCfjzQfkqcJ6Ujq4MFvAABNGZdwg4c3wNnX4fH8tBgO3p49HcWvOSiKEo/E4P0+irKhNJP0=
  on: 
    tags: true
    all_branches: true
  distributions: sdist
  user: bars-travis
python: 
- "2.7"
